### ISSUE TITLE
incorrect usage of "static" specifier

### ISSUE THREAD

**Issue by Njavris** [EdgarsMelnalksnis/BareMetalBinaryWatch#11]
declaration specifier "static" ensures that declared variable/structure or function is not visible outside current compilation unit, which is why adding them to header files are pointless and it clutters compiler, since it will declare a static prototype everywhere where it will be included.

**Comment by EdgarsMelnalksnis** [comment]
fixed in 929bd4c10ddad6d7cc11005af77044932a723c8a
