### ISSUE TITLE
incorrect use or "inline"

### ISSUE THREAD

**Issue by krisjans** [EdgarsMelnalksnis/BareMetalBinaryWatch#12]
For inline function to work it should be defined and used in the same object. You can't inline function from another object (at least you could not last time I checked). If you want to inline a function from another object then you must place definition of that function inside header file.
There is no use to add `inline` for function prototype in header file.

Note: `inline` is a _**recommendation**_ to compiler to try and insert whole function instead of calling it. But it comes with a cost - every time you call an inline function you insert whole function body (in binary form) instead of call to function. But do note that modern compilers and linkers have a lot of optimization going on and they often ignore (or override) `inline` directives.

**Comment by EdgarsMelnalksnis** [comment]
Removed "inline" keyword. As I understood, compiler is smarter than me and it will inline function if it is possible even without "inline" keyword. As I understand, "inline" keyword should be used, if the same function name is in more than one compilation unit.
