### ISSUE TITLE
Use descriptive names for header files

### ISSUE THREAD

**Issue by krisjans** [EdgarsMelnalksnis/BareMetalBinaryWatch#2]
Header file name should give an idea what's inside.
When `.h` file accompanies `.c` file, then it provides minimal information to re-use resources from that file - public function prototypes, public data types, public enums and structures. But only those, that describe either function arguments or function results. Constants that are used only inside particular file should not be exposed into header file.
`main.h` is rather odd name, `config.h` or `gpio_config.h` might be more descriptive.

**Comment by EdgarsMelnalksnis** [comment]
Fixed in 7884fd00c69be9283b8689ab3b93a5969c11a3b0 . main.h renamed to config.h
