### ISSUE TITLE
Say NO to magic numbers.

### ISSUE THREAD

**Issue by krisjans** [EdgarsMelnalksnis/BareMetalBinaryWatch#4]
https://github.com/EdgarsMelnalksnis/BareMetalBinaryWatch/blob/87168252b402325b46aec828e6fe763ed6048713/main.c#L11-L16
Use descriptive constants instead of 14, 15, 16, 17 etc. Even if you use them only once during initialization procedure. Check manufacturer header files, it is possible they already have #defines for most of bits.

**Comment by EdgarsMelnalksnis** [comment]
fixed in b0fcede6e610c0239299e3924b2c5fc97affef8c by defining descriptive constants instead of magic number
