### ISSUE TITLE
Add led layout in schematics or as separate image file;

### ISSUE THREAD

**Issue by krisjans** [EdgarsMelnalksnis/BareMetalBinaryWatch#5]
There is information about LED layout in schematics or in any other file.
If someone tries to understand what exactly is being displayed using those leds - there is no clue.

**Comment by EdgarsMelnalksnis** [comment]
fixded in dc454894b0c0765e1fa077e40f00a8730db021b8

**Comment by krisjans** [comment]
how about simply changing led placement in schematics (now on third page)? and add some light guide lines to indicate grid?

**Comment by krisjans** [comment]
I'm splitting hairs now. your solution is neat!

**Comment by krisjans** [comment]
BTW - that ASCII art in pdf's firs page - that would be nice comment in config.h

**Comment by EdgarsMelnalksnis** [comment]
Changed LED net names in schematic b4a8bf92b73c7132cf0f75e784eec559bdcbdea7
