### ISSUE TITLE
Use manufacturer's header files when possible.

### ISSUE THREAD

**Issue by krisjans** [EdgarsMelnalksnis/BareMetalBinaryWatch#9]
If possible use manufacturer's header files from SDK/DDK. Just describe in Makefile where SDK should be located and add that location to include file search path. If you can't do that, then include whole (unchanged) header files into your project. I would recommend to put them under some `external` folder to signal, that this is not your code.

You `config.h` file now contains mostly copy-pasted SOC register description. This is not your hardware config. This is SOC description and belongs to separate header file.
Only 6 lines (https://github.com/EdgarsMelnalksnis/BareMetalBinaryWatch/blob/main/include/config.h#L44-L49) describe project specific config. The rest is extract from manufacturers headers.

**Comment by EdgarsMelnalksnis** [comment]
As I understood from issue #3 I have to eliminate includes. Should I rewrite register descriptions in separate .h file or include manufacturer header files for SDK/DDK ?

**Comment by krisjans** [comment]
I think I did not express my concern clearly enough. As answered in https://github.com/EdgarsMelnalksnis/BareMetalBinaryWatch/issues/3#issuecomment-901854164 :
The problem is to `#include` unnecessary header files.
It is OK to have unused header files - especially from manufacturer. Bonus points if you put manufacturer header files into separate folder - just to reduce clutter.

**Comment by EdgarsMelnalksnis** [comment]
Added manufacturer header files dfa40d7f9325aaa01817e0827d90ede7fbc063ca , also renamed config.h to binaryWatch.h and added new source file binaryWatch.c where I will write all functions related to binary watch
